### ISSUE TITLE
request for releasing on indigo

### ISSUE THREAD

**Issue by k-okada** [PR2/pr2_common#234]

**Comment by UltronDestroyer** [comment]
Waiting on the release of http://wiki.ros.org/convex_decomposition

**Comment by k-okada** [comment]
its ready now !!! 
http://jenkins.ros.org/job/ros-indigo-convex-decomposition_binarydeb_trusty_amd64/

## 

◉ Kei Okada

**Comment by UltronDestroyer** [comment]
Thanks kei, I'll get to releasing this today.

**Comment by garaemon** [comment]
Is it released?

**Comment by UltronDestroyer** [comment]
Could not resolve rosdep key "ivcon". Will have to wait until that is released.

**Comment by UltronDestroyer** [comment]
I'll try and release the ivcon package from the pr2's repository to speed things up.

**Comment by UltronDestroyer** [comment]
See https://github.com/ros/ivcon/issues/1

**Comment by UltronDestroyer** [comment]
ivcon has been released, depending on urdfdom now. @k-okada do you know if this is required to depend on? I don't see it in the release list but I see urdfdom_py. on wiki.ros.org there said something about liburdfdom-dev, I think it's a system dep now so can stop using it for our ros depends?

**Comment by UltronDestroyer** [comment]
Ok, I've resolved all the keys. This package should be released soon :-)

**Comment by k-okada** [comment]
thank you!
