### ISSUE TITLE
Check for CATKIN_ENABLE_TESTING missing in pr2_description gtest declaration?

### ISSUE THREAD

**Issue by gavanderhoorn** [PR2/pr2_common#241]
Looks like `CMakeLists.txt` in `pr2_description` doesn't wrap the call to `catkin_add_gtest(..)` in a CATKIN_ENABLE_TESTING conditional block ([here](https://github.com/PR2/pr2_common/blob/21e0c1a5a5c4ec3a7a9527fa17dcafb8478edcc3/pr2_description/CMakeLists.txt#L94-L95)). On systems with no `gtest`, I believe this causes this package to fail the build.

**Comment by gavanderhoorn** [comment]
Relevant link: [catkin 0.6.14 documentation » How to do common tasks » Package format 2 (recommended) » Configuring gtest for C++](http://docs.ros.org/jade/api/catkin/html/howto/format2/gtest_configuration.html).

**Comment by gavanderhoorn** [comment]
Seems #238 already fixes this.

**Comment by gavanderhoorn** [comment]
Seeing as there is no issue for this, I'm actually going to keep this open until #238 is merged.

**Comment by trainman419** [comment]
Sorry; I converted some of these packages to catkin before that standard was established.

**Comment by gavanderhoorn** [comment]
No problem.

Merging #238 should fix it.
