### ISSUE TITLE
Changes to ROS wiki page for package

### ISSUE THREAD

**Issue by archielee** [PR2/pr2_common#249]
- [x] Add to ~~README~~ ROS wiki page that optenv must be set for Kinect if in use (KINECT or KINECT2)

**Comment by archielee** [comment]
No README for package, will put on the wiki page for pr2_description

**Comment by archielee** [comment]
@TheDash Would the pr2_description wiki page be the best place to put this information or would it be better off in the launch instructions?

**Comment by UltronDestroyer** [comment]
The pr2_description wiki would be best. See http://wiki.ros.org/PackageDocumentation

**Comment by archielee** [comment]
Changes have been made. Closing.
