### ISSUE TITLE
TIFFFieldWithTag warnings with pr2_description

### ISSUE THREAD

**Issue by davetcoleman** [PR2/pr2_common#257]
Similar to https://github.com/PR2/pr2_common/issues/256, I'm getting hundreds of these warnings:

> TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
> TIFFFieldWithTag: Internal error, unknown tag 0x829a.

**Comment by Kukanani** [comment]
A "quick" way to fix a lot of these errors is to change the TIFs to PNGs, and update the corresponding .dae files.

**Comment by airballking** [comment]
I am having the same problem when using PR2's URDF on Kinetic. 

@davetcoleman Why did you close this issue? Is there a fix available?

**Comment by davetcoleman** [comment]
I thought I had fix this, but looking at my commit history to this repo I think I only fixed other things...

**Comment by fgq1992** [comment]
I met the same problem. Is there anyone who solved this problem.  My ros version is kinetic.

**Comment by airballking** [comment]
I am not aware of any fix. @davetcoleman do you have a fork with a working fix somewhere?

**Comment by davetcoleman** [comment]
No, I never found a fix

**Comment by DLu** [comment]
Reported upstream here: https://github.com/ros-visualization/rviz/issues/1201
Seems to be ignorable for now.

**Comment by kvnptl** [comment]
> A "quick" way to fix a lot of these errors is to change the TIFs to PNGs, and update the corresponding .dae files.

It works, i guess. After replacing .tif with .png, I am not getting any TIFFField error.

**Comment by v4hn** [comment]
> It works, i guess. After replacing .tif with .png, I am not getting any TIFFField error.

How about a pull-request?
