### ISSUE TITLE
Release request in Indigo

### ISSUE THREAD

**Issue by knorth55** [PR2/pr2_common#268]
indigo's latest is `1.11.14`, and there are many changes from the last release.
We really want the new release.

**Comment by furushchev** [comment]
+1 for porting features on `kinetic-devel` into `indigo` especially https://github.com/PR2/pr2_common/commit/b4459bd6c0b23f1faa60ba5a15c660d3fe2dfa9b 
cc: @k-okada

**Comment by k-okada** [comment]
done
https://github.com/ros/rosdistro/pull/17786
https://github.com/ros/rosdistro/pull/17785

this bumps version from 1.11.x to 1.12.x, so it is huge change, be careful
