### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by sthoduka** [PR2/pr2_common#283]
Could you create a release for Noetic? thanks

**Comment by v4hn** [comment]
@k-okada What are your plans for noetic releases?

**Comment by k-okada** [comment]
I have checked noetic with travis, 
- pr2_common #284  (https://github.com/ros/rosdistro/pull/26154)
- pr2_mechanism https://github.com/PR2/pr2_mechanism/pull/342
works as it is. And 
- pr2_simulator https://github.com/PR2/pr2_simulator/pull/148
need to fix `package.xml` and `CMakeLists.txt` for noetic build.

**Comment by sthoduka** [comment]
thanks!
