### ISSUE TITLE
noetic-devel branch

### ISSUE THREAD

**Issue by ashuRMS** [PR2/pr2_common#293]
I am using ROS-Noetic. I want to clone this repository.  I could not find any branch related to noetic-devel. Is there any other repository for noetic-devel? How to resolve this issue? Please guide me.

**Comment by v4hn** [comment]
Did you find any problem using the `melodic-devel` branch? To the best of my knowledge noetic does not need any patches. My group has [some patches on top](https://github.com/PR2/pr2_common/compare/melodic-devel...TAMS-Group:pr2_common:noetic-devel-tams), but those are specific to our hardware setup.

**Comment by ashuRMS** [comment]
I cloned the `melodic-devel` branch of this repository. After doing catkin make, I needed some standalone packages, I installed them, and everything went fine. Thank you .
